$(document).ready(function(){
    $('.text').click(function(){
        $('.one').hide(1000);
    });
});
$(document).ready(function(){
    $('h3').click(function(){
        $(this).hide(1000);
    });
});